baseURL = "https://opleonnn.github.io"
languageCode = "en-us"
title = "Leon"
theme = "Ink"
paginate = 5

copyright = "© Leon."

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = "学无止境"

	# Optional 64x64 avatar image.
	avatar = "https://avatars0.githubusercontent.com/u/48051254?s=460&u=09cd38c785b674756a705c9958cfc5c0245c6936&v=4"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "主页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts"
weight = 2

[[menu.main]]
name = "关于"
url = "/about"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/opleonnn"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
